import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable

WebUI.delay(10)

WebUI.navigateToUrl('https://qa.medisource.com/patientcare/9B1E9547-DAF3-40F4-820E-C5881066FBCA/C8456552-AA09-4EBF-B4EC-9A3EB6FBF25B/2019/oasis/medical/history/roc/B8A507ED-973F-4CB5-82DB-48318F1127A4/9B1E9547-DAF3-40F4-820E-C5881066FBCA')
// SENSORY
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Sensory1'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Sensory2'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Sensory3'), FailureHandling.CONTINUE_ON_FAILURE)
// INTEGUMENTARY
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Integumentary1'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Integumentary2'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Integumentary3'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_IntegumentaryOthers'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('OASIS ROC/Medical_History/med_History_IntegumentaryOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
// RESPIRATORY
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Respiratory1'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Respiratory2'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Respiratory3'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Respiratory4'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_RespiratoryOthers'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('OASIS ROC/Medical_History/med_History_RespiratoryOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
// CARDIO
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio1'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio2'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio3'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio4'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio5'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio6'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Cardio7'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_CardioOthers'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('OASIS ROC/Medical_History/med_History_CardioOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
// GASTRO
WebUI.delay(2)
WebUI.click(findTestObject('OASIS ROC/Medical_History/med_History_Gastro1'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Gastro2'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Gastro3'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Gastro4'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Gastro5'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_GastroOthers'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_GastroOthers'), 'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
// GENITO
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito3'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito4'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito5'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Genito6'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_GenitoOthers'), FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_GenitoOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
//NEURO
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro3'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro4'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro5'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro6'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro7'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro8'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Neuro9'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_NeuroOthers'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_NeuroOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
// MUSCU
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_history_Muscu3'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu4'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu5'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu6'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu7'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Muscu8'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_MuscuOthers'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_MuscuOthers'), 'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
// CIRCU
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Circu1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Circu2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Circu3'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_CircuOthers'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_CircuOthers'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
// Other Medical History
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHis'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHisInput1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHisInput1'), 'Sample Data1',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHis2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHisInput2'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_OtherMedHisInput2'), 'Sample Data 2',  FailureHandling.CONTINUE_ON_FAILURE)
//Past Surgical History
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_PastSurgicalDate1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_PastSurgicalDate1'), '2019',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_PastSurgicalProc1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_PastSurgicalProc1'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
//Hospitalizations
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Hospi1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Hospi1'), 'January 01, 2019',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HospiReason1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HospiReason1'), 'Sample Data', FailureHandling.CONTINUE_ON_FAILURE)
//Influenza Vaccine (October to March)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Influenza_NoReason'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Influenza_NoReasonInput'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Influenza_NoReasonInput'),'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Influenza_Offered'),  FailureHandling.CONTINUE_ON_FAILURE)
//Pneumonia Vaccine (every 5 years)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Pneumonia_YesDate'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Pneumonia_YesDateInput'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Pneumonia_YesDateInput'),'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Pneumonia_Agreed_PCP'),  FailureHandling.CONTINUE_ON_FAILURE)
//Other Immunizations and Tests
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_ShinglesYes'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_ShinglesInput'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_ShinglesInput'), 'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_TB'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_TBinput'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_Other_Immunization_TBinput'),'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
//Health Screening 
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamType1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamType1'),'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamDate1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamDate1'), '2019', FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamResult1'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_ExamResult1'),'Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_HS_AllergiesNKA'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_DateLastContact'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_DateLastContact'),'2019',  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_DateLastVisit'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_DateLastVisit'), '2019' ,  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.click(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_ReasonForContact'),  FailureHandling.CONTINUE_ON_FAILURE)
WebUI.delay(2)
WebUI.setText(findTestObject('Object Repository/OASIS ROC/Medical_History/med_History_RecentF2F_ReasonForContact'), ' Sample Data',  FailureHandling.CONTINUE_ON_FAILURE)














