<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M0069</name>
   <tag></tag>
   <elementGuidId>38a2cdc2-6667-456c-90c6-1b2de0128278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#code</value>
   </webElementProperties>
</WebElementEntity>
